version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: cinema-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: cinemadb
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cinema-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  sonarqube:
    image: sonarqube:community
    container_name: cinema-sonarqube
    restart: unless-stopped
    environment:
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - cinema-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: cinema-api
    restart: unless-stopped
    environment:
      SERVER_PORT: ${SERVER_PORT:-8082}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cinemadb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-root}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-}
      SPRING_FLYWAY_REPAIR_ON_MIGRATE: "true"
    ports:
      - "${SERVER_PORT:-8082}:8082"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - cinema-network
volumes:
  mysql_data:
    driver: local
  sonarqube_data:
    driver: local
  sonarqube_extensions:
    driver: local
  sonarqube_logs:
    driver: local

networks:
  cinema-network:
    driver: bridge
